spring:
  application:
    name: mall-server
  cloud:
    consul:
      host: localhost
      port: 8500
#  zipkin:
#    base-url: http://localhost:9411/
#    sender:
#      # 指定用什么方式上报数据给 zipkin server
#      type: web
#    locator:
#      discovery:
#        enabled: false
#  sleuth:
#    sampler:
#      # 配置数据的采样率 默认值
#      probability: 1.0

# 暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# feign相关配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled:  false